version: '3'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "./redisdb:/data"
    networks:
      - redis

networks:
  redis:
